apiVersion: v1
kind: Service
metadata:
  name: llmops-service
  namespace: llmops
  labels:
    app: llmops-app
spec:
  type: LoadBalancer
  selector:
    app: llmops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080