apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-deployment
  namespace: llmops
  labels:
    app: llmops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llmops-app
  template:
    metadata:
      labels:
        app: llmops-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: application
        image: public.ecr.aws/c3q7e5h6/llm_mlops_ids721
        ports:
        - name: app-port
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
