name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test, Lint, and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust and dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test
        run: cargo test

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Format
        run: cargo fmt

  deploy:
  name: Deploy
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on pushes to main branch

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build.sh
      run: deploy/build.sh


