name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test, Lint, and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust and dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install torch
        run: pip3 install torch==2.1.0+cpu --index-url https://download.pytorch.org/whl/cpu --break-system-packages

      - name: Set env
        run: echo "LIBTORCH_USE_PYTORCH=1" >> $GITHUB_ENV

      - name: Test
        run: cargo test

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Format
        run: cargo fmt

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on pushes to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build.sh
        run: deploy/build.sh -u public.ecr.aws/c3q7e5h6/llm_mlops_ids721 -p -r us-east-1




