name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test, Lint, and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust and dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install torch
        run: pip3 install torch==2.1.0+cpu --index-url https://download.pytorch.org/whl/cpu --break-system-packages

      - name: Set libtorch env
        run: echo "LIBTORCH_USE_PYTORCH=1" >> $GITHUB_ENV

      - name: Test
        run: cargo test

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Format
        run: cargo fmt

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on pushes to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create ECR Repository
        id: create_ecr_repo
        run: |
          aws ecr create-repository --repository-name my-ecr-repo-rust
          ECR_URL=$(aws ecr describe-repositories --repository-names my-ecr-repo-rust --query 'repositories[0].repositoryUri' --output text)
          echo "::set-env name=ECR_URL::$ECR_URL"

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

      - name: Build and Tag Docker Image
        run: |
          ./build.sh -u $ECR_URL

      - name: Push Docker Image to Amazon ECR
        run: docker push ${{ env.ECR_URL }}:latest
